{{- if .Values.postgres.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ldap-sync.fullname" . }}-allow-postgres
  labels:
    {{- include "ldap-sync.labels" . | nindent 4 }}
spec:
  # Select the postgres pod deployed by the subchart
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "ldap-sync.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
