// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hook": {
            "post": {
                "description": "Process and transform LDAP entries based on their type.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Process LDAP hook payload",
                "parameters": [
                    {
                        "description": "LDAP Hook Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HookResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DerivedSearch": {
            "type": "object",
            "properties": {
                "baseDN": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "oneshot": {
                    "type": "boolean"
                },
                "refresh": {
                    "type": "integer"
                }
            }
        },
        "main.HookRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "type": "string"
                }
            }
        },
        "main.HookResponse": {
            "type": "object",
            "properties": {
                "bindings": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "dependencies": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "derived": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DerivedSearch"
                    }
                },
                "reset": {
                    "type": "boolean"
                },
                "transformed": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
